export const FETCH_SINGLE_BOOK_REQUEST = "FETCH_SINGLE_BOOK_REQUEST";
export const FETCH_SINGLE_BOOK_SUCCESS = "FETCH_SINGLE_BOOK_SUCCESS";
export const FETCH_SINGLE_BOOK_FAILURE = "FETCH_SINGLE_BOOK_FAILURE";
